//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Cropper.rc
//
#define ID_NAV_NOSELECT                 2
#define ID_NAV_SELECTED                 3
#define ID_NAV_CHECKBLACK               6
#define ID_NAV_CHECKRED                 7
#define ID_NAV_NONE                     8
#define ID_NAV_NONESEL                  9
#define ID_NAV_DRAGDROP                 10
#define ID_NAV_ORIGS                    11
#define ID_NAV_PROC                     12
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_UPDATE_DLGBAR                102
#define IDC_LINK                        104
#define IDC_MAILTO                      105
#define IDR_MAINFRAME                   128
#define IDB_SELECTION                   129
#define IDS_SIZING                      129
#define IDS_NOPICTURES                  130
#define IDD_SAVE                        131
#define IDS_SAMEFOLDER                  131
#define IDS_SAVE_ERROR                  132
#define IDS_READONLY                    133
#define IDD_BULKSAVE                    134
#define IDS_OVERWRITE                   134
#define IDS_VERSION                     135
#define IDS_WEBSITE_URL                 136
#define IDR_SELTREE_MENU                137
#define IDS_DRAGDROP                    137
#define IDD_RESIZE                      138
#define IDS_REMIND_START                138
#define IDS_REMIND_END                  139
#define IDD_SETSPECS                    140
#define IDS_REMIND_OVER                 140
#define IDS_PURCHASE_URL                141
#define IDS_MAILTO                      142
#define IDD_ROTATE                      143
#define IDS_KEY_ERROR                   143
#define IDB_SPLASH                      144
#define IDS_RIGHTS_ERROR                144
#define IDB_ERROR                       145
#define IDS_WRITE_ERROR                 145
#define IDS_ALTPURCHASE_URL             146
#define IDR_PICTURE_MENU                147
#define IDS_EBAY_OVER                   147
#define IDS_TREE_PHOTOS                 148
#define IDS_TREE_ORIGS                  149
#define IDB_LOGO                        150
#define IDR_VIEW_POPUP                  150
#define IDS_TREE_PROCS                  150
#define IDS_MAX_SIZE                    151
#define IDD_DIALOG1                     154
#define IDD_REMINDER                    154
#define IDB_FILLER                      156
#define IDB_WHITE                       158
#define IDB_YELLOW                      158
#define IDB_RED                         159
#define IDB_BUYNOW                      160
#define IDB_BLACK                       161
#define IDD_REGISTER                    162
#define IDB_DRAGDROP                    165
#define IDC_NAME                        1000
#define IDC_CHK_NEXT                    1002
#define IDC_CBO_FOLDER                  1003
#define IDC_ORIGINAL_PATH               1005
#define IDC_TARGET_PATH                 1006
#define IDC_IMAGE_NAME                  1007
#define IDC_IMAGE_INFO                  1008
#define IDC_CHK_REDUCE                  1009
#define IDC_CBO_UNITS                   1010
#define IDC_MAX_HEIGHT                  1011
#define IDC_MAX_WIDTH                   1012
#define IDC_SPIN_HEIGHT                 1013
#define IDC_SPIN_WIDTH                  1014
#define IDC_CHK_OVERWRITE               1015
#define IDC_COUNT                       1016
#define IDC_PROCESS_FOLDER              1017
#define IDC_MAX_SIZE                    1017
#define IDC_BROWSE                      1018
#define IDC_SETSIZE                     1020
#define IDC_CHK_AUTO                    1021
#define IDC_SIZING                      1022
#define IDC_ANGLE                       1023
#define IDC_LEVEL                       1024
#define IDC_FRAME                       1025
#define IDC_BACKGROUND                  1026
#define IDC_URL                         1028
#define IDC_VERSION                     1029
#define IDC_ORIGINAL_CNT                1031
#define IDC_TARGET_CNT                  1032
#define IDC_UNITS                       1033
#define IDC_FILLER                      1035
#define IDC_PRICE                       1036
#define IDC_NATION                      1037
#define IDC_BACK                        1038
#define IDC_MESSAGE                     1039
#define IDC_COPYRIGHT                   1040
#define IDC_REGNAME                     1041
#define IDC_REGCOMPANY                  1042
#define IDC_REGKEY                      1043
#define IDC_SHOWKEY                     1044
#define IDC_PURCHASE                    1046
#define IDC_LICENSE                     1047
#define IDC_BUTTON1                     1051
#define ID_FILE_OPENPROCESSED           32771
#define ID_EDIT_ROTATELEFT              32773
#define ID_EDIT_ROTATERIGHT             32774
#define ID_POSITION_TOP                 32775
#define ID_EDIT_FLIPVERTICAL            32776
#define ID_VIEW_NEXT                    32777
#define ID_VIEW_PREVIOUS                32778
#define ID_VIEW_ORIGINALS               32779
#define ID_VIEW_REDUCED                 32781
#define ID_VIEW_PROCESSED               32782
#define ID_VIEW_CROPPINGTOOL            32784
#define ID_NAV_FOLDERCLOSE              32793
#define ID_NAV_FOLDEROPEN               32794
#define ID_EDIT_TRUE                    32798
#define ID_EDIT_SIZE                    32799
#define ID_EDIT_SET                     32800
#define ID_NAV_PFOLDERCLOSE             32801
#define ID_NAV_PFOLDEROPEN              32802
#define ID_FILE_RESIZEALL               32803
#define ID_POPUP_OPEN                   32809
#define ID_POPUP_PROCESSED              32811
#define ID_POPUP_REFRESH                32812
#define ID_EDIT_ROTATEADJUST            32821
#define ID_EDIT_FLIPHORIZONTAL          32823
#define ID_RESTORE_PICTURE              32828
#define ID_POPUP_NEXT                   32829
#define ID_POPUP_PREVIOUS               32830
#define ID_BUTTON32845                  32845
#define ID_INDICATOR_POS                59142
#define ID_INDICATOR_CROP               59143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32854
#define _APS_NEXT_CONTROL_VALUE         1052
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
